// Code generated by Slice Machine. DO NOT EDIT.

import Biography from './Biography/index.svelte';
import Hero from './Hero/index.svelte';
import RichText from './RichText/index.svelte';

export const components = {
	biography: Biography,
	hero: Hero,
	rich_text: RichText
};
